name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Entrando na pasta do projeto
      run: cd ./my-react-app
    - name: Instalar dependências
      run: npm install
    - name: Construir a aplicação React
      run: npm run build
    - name: Construir e rodar Docker
      run: |
        docker build -t my-react-app .
        docker run -d -p 80:80 my-react-app